/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RepartidorRouteImport } from './routes/repartidor'
import { Route as NuevoPedidoRouteImport } from './routes/nuevo-pedido'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RepartidorGananciasRouteImport } from './routes/repartidor.ganancias'
import { Route as PedidoIdRouteImport } from './routes/pedido.$id'

const RepartidorRoute = RepartidorRouteImport.update({
  id: '/repartidor',
  path: '/repartidor',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevoPedidoRoute = NuevoPedidoRouteImport.update({
  id: '/nuevo-pedido',
  path: '/nuevo-pedido',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepartidorGananciasRoute = RepartidorGananciasRouteImport.update({
  id: '/ganancias',
  path: '/ganancias',
  getParentRoute: () => RepartidorRoute,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cliente': typeof ClienteRoute
  '/nuevo-pedido': typeof NuevoPedidoRoute
  '/repartidor': typeof RepartidorRouteWithChildren
  '/pedido/$id': typeof PedidoIdRoute
  '/repartidor/ganancias': typeof RepartidorGananciasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cliente': typeof ClienteRoute
  '/nuevo-pedido': typeof NuevoPedidoRoute
  '/repartidor': typeof RepartidorRouteWithChildren
  '/pedido/$id': typeof PedidoIdRoute
  '/repartidor/ganancias': typeof RepartidorGananciasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cliente': typeof ClienteRoute
  '/nuevo-pedido': typeof NuevoPedidoRoute
  '/repartidor': typeof RepartidorRouteWithChildren
  '/pedido/$id': typeof PedidoIdRoute
  '/repartidor/ganancias': typeof RepartidorGananciasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cliente'
    | '/nuevo-pedido'
    | '/repartidor'
    | '/pedido/$id'
    | '/repartidor/ganancias'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/cliente'
    | '/nuevo-pedido'
    | '/repartidor'
    | '/pedido/$id'
    | '/repartidor/ganancias'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/cliente'
    | '/nuevo-pedido'
    | '/repartidor'
    | '/pedido/$id'
    | '/repartidor/ganancias'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ClienteRoute: typeof ClienteRoute
  NuevoPedidoRoute: typeof NuevoPedidoRoute
  RepartidorRoute: typeof RepartidorRouteWithChildren
  PedidoIdRoute: typeof PedidoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/repartidor': {
      id: '/repartidor'
      path: '/repartidor'
      fullPath: '/repartidor'
      preLoaderRoute: typeof RepartidorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nuevo-pedido': {
      id: '/nuevo-pedido'
      path: '/nuevo-pedido'
      fullPath: '/nuevo-pedido'
      preLoaderRoute: typeof NuevoPedidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repartidor/ganancias': {
      id: '/repartidor/ganancias'
      path: '/ganancias'
      fullPath: '/repartidor/ganancias'
      preLoaderRoute: typeof RepartidorGananciasRouteImport
      parentRoute: typeof RepartidorRoute
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RepartidorRouteChildren {
  RepartidorGananciasRoute: typeof RepartidorGananciasRoute
}

const RepartidorRouteChildren: RepartidorRouteChildren = {
  RepartidorGananciasRoute: RepartidorGananciasRoute,
}

const RepartidorRouteWithChildren = RepartidorRoute._addFileChildren(
  RepartidorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ClienteRoute: ClienteRoute,
  NuevoPedidoRoute: NuevoPedidoRoute,
  RepartidorRoute: RepartidorRouteWithChildren,
  PedidoIdRoute: PedidoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
